#!/bin/bash

# This script is used to start reper
# call this script as
# reper <job>
# with <job> as the next part to execute (jelly, kmerFilter, Trinity, cluster, classify, quantify, landscape)
# the jobs following the givien one are executed automatically


## read config
export reperDir="$PWD"
source reper.conf
ulimit -v "$maxMemoryKB"

## define next job
nextJob="$1"

## run scripts
case "$nextJob" in
    jelly) "$scrDir"/01_Jellyfish.sh
	   exit 0
	   ;;
    kmerFilter) "$scrDir"/02_Kmer-filter.sh
		exit 0
		;;
    Trinity) "$scrDir"/03_Trinity.sh
	     exit 0
	     ;;
    cluster) "$scrDir"/04_cd-hit.sh 
	     exit 0
	     ;;
    classify) "$scrDir"/05_Classifier.sh
	      exit 0
	      ;;
    quantify) "$scrDir"/06_Bowtie.sh 
	      exit 0
	      ;;
    landscape) "$scrDir"/07_build_landscape.pl --clstr "$CLUSTEROUT".clstr --fasta "$CLASSIFYOUT" --bam "$QUANTOUT" --coverage "$COVERAGE" --samtools "$samtools"
	       exit 0
	       ;;
    configure-REdat) "$scrDir"/configure-REdat.sh
		     exit 0
		     ;;
    configure-repbase) perl "$scrDir"/configure-repbase.pl $2 $3 $4
		       exit 0
		       ;;
    *) echo "$STARTJOB is not a valid job name!"
       echo "please select one of the following:"
       echo "jelly, kmerFilter, Trinity, cluster, classify, quantify, landscape"
       exit 1
       ;;
esac

