#!/bin/bash

# This script is used to start reper
# call this script as
# reper <job>
# with <job> as the next part to execute (jelly, kmerFilter, Trinity, cluster, classify, quantify, landscape)
# the jobs following the givien one are executed automatically


## read config
source ./reper.conf
export reperDir
ulimit -v "$maxMemoryKB"

## define next job
nextJob="$1"

## run scripts
case "$nextJob" in
    jelly) "$scrDir"/01_Jellyfish.sh
	   exit 0
	   ;;
    kmerFilter) "$scrDir"/02_Kmer-filter.sh
		exit 0
		;;
    Trinity) "$scrDir"/03_Trinity.sh
	     exit 0
	     ;;
    cluster) "$scrDir"/04_cd-hit.sh 
	     exit 0
	     ;;
    classify) "$scrDir"/05_Classifier.sh
	      exit 0
	      ;;
    quantify) "$scrDir"/06_Bowtie.sh 
	      exit 0
	      ;;
    landscape) "$scrDir"/07_build_landscape.pl --clstr "$CLUSTEROUT".clstr --fasta "$CLASSIFYOUT" --bam "$QUANTOUT" --coverage "$COVERAGE" --samtools "$samtools"
	       exit 0
	       ;;
    configure-REdat) "$scrDir"/configure-REdat.sh
		     exit 0
		     ;;
    configure-refseq) "$scrDir"/configure-refseq.sh
		     exit 0
		     ;;
    configure-repbase) mkdir -p "$3"
		       perl "$scrDir"/configure-repbase.pl "$2" "$3" "$4"
		       "$makeblastdb" -dbtype 'nucl' -in "$2".fa
		       exit 0
		       ;;
    print-env) echo "#####################"
	       echo "printing variables"
	       echo "reperDir: $reperDir"
	       echo "conf-file: "$(realpath reper.conf)
	       echo "scrDir: $scrDir"
	       echo "depDir: $depDir"
	       echo "dbDir: $dbDir"
	       echo "max-CPU: $MAXTHREADS"
	       echo "max-MEM: $MAXMEMORY"
	       echo "input: $READS1 $READS2"
	       exit 0
	       ;;
    *) echo "$STARTJOB is not a valid job name!"
       echo "please select one of the following:"
       echo "jelly, kmerFilter, Trinity, cluster, classify, quantify, landscape"
       exit 1
       ;;
esac

